/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  ILiveFeedOracleId,
  ILiveFeedOracleIdInterface,
} from "../ILiveFeedOracleId";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "string",
        name: "metadata",
        type: "string",
      },
    ],
    name: "LogMetadataSet",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "timestamp",
        type: "uint256",
      },
    ],
    name: "_callback",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "getResult",
    outputs: [
      {
        internalType: "uint256",
        name: "result",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class ILiveFeedOracleId__factory {
  static readonly abi = _abi;
  static createInterface(): ILiveFeedOracleIdInterface {
    return new utils.Interface(_abi) as ILiveFeedOracleIdInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ILiveFeedOracleId {
    return new Contract(address, _abi, signerOrProvider) as ILiveFeedOracleId;
  }
}
