/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IOracleId, IOracleIdInterface } from "../IOracleId";

const _abi = [
  {
    inputs: [],
    name: "getResult",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IOracleId__factory {
  static readonly abi = _abi;
  static createInterface(): IOracleIdInterface {
    return new utils.Interface(_abi) as IOracleIdInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IOracleId {
    return new Contract(address, _abi, signerOrProvider) as IOracleId;
  }
}
