/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  RegistryManager,
  RegistryManagerInterface,
} from "../RegistryManager";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "_changer",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "_newRegistryAddress",
        type: "address",
      },
    ],
    name: "LogRegistryChanged",
    type: "event",
  },
  {
    inputs: [],
    name: "getRegistry",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_registry",
        type: "address",
      },
    ],
    name: "setRegistry",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class RegistryManager__factory {
  static readonly abi = _abi;
  static createInterface(): RegistryManagerInterface {
    return new utils.Interface(_abi) as RegistryManagerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): RegistryManager {
    return new Contract(address, _abi, signerOrProvider) as RegistryManager;
  }
}
